### ISSUE TITLE
Allow access to all parts of the Cuckoo report

### ISSUE THREAD

**Issue by JannisTriesToCode** [scVENUS/PeekabooAV#119]
Currently it is only possible to access predefined parts of the Cuckoo report. More specifically those listed as properties in the following [class](https://github.com/scVENUS/PeekabooAV/blob/25fc4b963786677996d8e46c36613298ba758728/peekaboo/toolbox/cuckoo.py#L501).

To further train the rule set, it needs to have full access to the report.

**Comment by Jack28** [comment]
Hello @JannisTriesToCode 

thank you for opening an issue.
Which parts of the cuckoo report do you need access to?

We deliberately chose not to export the whole report structure as handed to us by Cuckoo because it constitutes external data which is not under our control. Instead we provide specific properties exposing discrete report elements.

**Comment by Jack28** [comment]
Any news on this?

**Comment by JannisTriesToCode** [comment]
Not yet. It might not even be necessary anymore. I will close the issue for now.
