### ISSUE TITLE
Question: Analysis Result 

### ISSUE THREAD

**Issue by MigliS** [scVENUS/PeekabooAV#15]
Hi Felix

I'v got only a small question about the four analysis result states _inProgress_, _uknown_, _ignored_, _bad_.
Actually I only know what _inProgress_ and _bad_ mean. But the other two I cannot assing to something. _unknown_ maybe that the attachment is good but with _ignored_ I don't have a clue.

Cloud you help me out there? 

Thank you for your help.
Best
Michael

**Comment by Jack28** [comment]
Hi Michael,

the analysis results used in `Sample` objects and saved in the database stand for the following:

- `inProgress`: this sample is currently being analysed
- `unchecked`: is just the default value which is expected to always get replaced by one of the others
- `unknown`: this sample was successfully analysed and didn't trigger any events to identify evil
- `ignored`: this sample has not been analysed (e.g. because of the whitelist)
- `checked`: is only used for testing since we don't get an actual result here
- `bad`: this sample has been recognised as malicious

The `Enum` is defined in `peekaboo/ruleset/__init__.py`. Search the code for those results to get a better understanding of where they're used.

Important question thanks
Felix
