### ISSUE TITLE
Peekaboo accidentally thinks cuckoo produced some errors if there aren't

### ISSUE THREAD

**Issue by Clevero** [scVENUS/PeekabooAV#59]
Peekabo marks the attachments as bad because there "is" an error. But according to Analysis and Cuckoo log there isn't one

## Expected Behavior
If there isn't an error, peekaboo shouldn't mark it as bad (current intended behavior of peekaboo)

## Current Behavior
Peekaboo marks the attachment as bad

## Possible Solution
I don't see any errors in the logs mentioned above
But I do see, that the log doesn't contain the string "analysis completed successfully"
If I understood it correctly, peekaboo determines with that string if the analysis has failed?
https://github.com/scVENUS/PeekabooAV/blob/a42f22ab70329f0c9f4b568ce61acbe5f3bddcc5/peekaboo/toolbox/cuckoo.py#L440

**Hope this issue belongs to Peekaboo, or should I create an issue at cuckoo?**

## Steps to Reproduce

1. Instance installed with the latest version of the installer
2. Attachment: [f.docx](https://github.com/scVENUS/PeekabooAV/files/2626655/f.docx)

Analysis: [85.zip](https://github.com/scVENUS/PeekabooAV/files/2626667/85.zip)

## Context (Environment)
Some versions before, there wasn't such a problem. But sadly I cannot say which version was installed

Thank you for your help!!

**Comment by Clevero** [comment]
Retested it with my last version installed, should be https://github.com/scVENUS/PeekabooAV-Installer/commit/c0167da5494ce48ac8b5c5df0707a14047a245a7

Also this behavior. Strange... Will see where my configuration is wrong and report back

**Comment by michaelweiser** [comment]
Your cuckoo logs indeed look good. `report.json` section`debug/cuckoo` actually does contain the success indicator.

Can you provide the Peekaboo log for the analysis in question?

**Comment by Clevero** [comment]
Sorry, gave you the wrong exported report. I've noticed that while searching for the peekaboo log of that analysis.

Correct report: [143.zip](https://github.com/scVENUS/PeekabooAV/files/2652926/143.zip)
Peekaboo log excerpt: [f.peekaboo.log.txt](https://github.com/scVENUS/PeekabooAV/files/2652936/f.peekaboo.log.txt)

**Comment by Clevero** [comment]
I created a fresh instance of peekaboo in a new 18.04 VM with the latest installer and the error persists
VM's, Postfix and AmaVis (in a sperated vm) stayed the same

Will need to modify my local  PeekabooAV/peekaboo/toolbox/cuckoo.py until version 1.7

**Comment by michaelweiser** [comment]
@Clevero: I've been working to make Peekaboo correctly report failed analyses as failed instead as bad. If you like, you can check out https://github.com/michaelweiser/PeekabooAV/tree/ruleset to see if that solves your problem.

**Comment by michaelweiser** [comment]
@Clevero: https://github.com/michaelweiser/PeekabooAV/tree/ruleset now contains code that allows message matching of rule cuckoo_analysis_failed to be configured. With this you can declare some other messages in your report success indicators and prevent the rule from failing your analyses. See ``ruleset.conf.sample`` for docs.

However, looking at your report I see message ``end of analysis reached!` which according to the Cuckoo source means that the analysis not only ran beyond the timeout but refused to be shut down by the agent and ran into the critical timeout as well at which point Cuckoo just shut down the VM. This IMO is a clear indicator of failure because analysis did indeed not finish and had to be aborted. Therefore no conclusions about the malevolence of the sample can reliably be made based on this. So I'd recommend to let these continue to fail and handle failed scans in AMaViS as outlined above or look into why this analysis gets stuck so badly.

But, with the new config option it's up to you to decide. If you don't have any objections I'd merge the code to master and close this issue here. Okay?

**Comment by Clevero** [comment]
👍 

Will investigate. Thought that is normal behavior since a process is running that is not stopping by itself (Word for example), so cuckoo does not know if there is coming any harmful routine and waits for the timeout of the machine. Oversaw that the cuckoo agent refused to shut down the VM within a certain amount of time. Thanks for the feedback

Currently rebuilding my instance inside a vApp on vSphere

**Comment by michaelweiser** [comment]
FWIW: All the changes referenced here are now merged to master.

**Comment by Clevero** [comment]
Thanks for pointing out the problem with ```end of analysis reached!``` :)

Could resolve it
I switched my VM's from Windows 7 x86 to x64 (should have followed the recommendations from the cuckoo project for OS versions...)
It seems to me that the agent crashed at some point and did not received the command to shutdown

While debugging I found also out that the new Agent version 0.9 has some issues with my installation
